---
title: "AutoAff"
author: "Yi Lian"
date: '2019-07-21'
output: word_document
---



```{r cars}
# set.seed(29010719)
# names <- c(LETTERS, letters)
# n <- length(names)
# aff <- sapply(names, function(x){paste("U", x, sep = "")})
# 
# a <- as.character(sample(aff, n, replace = TRUE))
# b <- as.character(c(sample(aff, n - 8, replace = TRUE), rep(NA, 8)))
# c <- as.character(c(sample(aff, n - 20, replace = TRUE), rep(NA, 20)))
# 
# data <- data.frame(names, a, b, c)
# 
# 
# for (i in 1:32) {
#   if (data[i,1] == data[i,2] | data[i,1] == data[i,3] | data[i,2] == data[i,3]) {
#     print(i)
#   }
# }
# 
# for (i in 1:44) {
#   if (data[i,1] == data[i,2]) {
#     print(i)
#   }
# }
# 
# data[11, 3] = "UZ"
# data <- data[sample(1:n), ]

AutoAff <- function(X, aff1, aff2, aff3, name) {
  mat <- as.matrix(X[, c(aff1, aff2, aff3)])
  aff <- na.exclude(unique(as.character(as.vector(t(mat)))))
  n.aff <- length(aff)
  aff <- aff[1:n.aff]
  
  mat <- cbind(mat, rep(NA, dim(X)[1]))
  for (i in 1:dim(X)[1]) {
    aa <- which(aff == mat[i, 1])
    bb <- which(aff == mat[i, 2])
    cc <- which(aff == mat[i, 3])
    if (length(aa) == 0) {
      mat[i, 1] <- mat[i, 2] <- mat[i, 3] <- mat[i, 4] <- ""
    } else {
      if (length(bb) != 0){
        if (length(cc) == 0) {
          mat[i, 1] <- aff[min(c(aa, bb))]
          mat[i, 2] <- aff[max(c(aa, bb))]
          mat[i, 4] <- paste(min(c(aa, bb)), ",", max(c(aa, bb)), sep = "")
        }
        if (length(cc) != 0) {
          order <- sort(c(aa, bb, cc))
          mat[i, 1] <- aff[order[1]]
          mat[i, 2] <- aff[order[2]]
          mat[i, 3] <- aff[order[3]]
          if (order[2] - order[1] == 1 & order[3] - order[2] == 1) {
            mat[i, 4] <- paste(order[1], "-", order[3], sep = "")
          } else {
            mat[i, 4] <- paste(order[1],",", order[2], ",", order[3], sep = "")
          }
        }
      } else {
        mat[i, 4] <- paste(aa)
      }
    }
  }
  
  data[, "a"] <- mat[, 1]
  data[, "b"] <- mat[, 2]
  data[, "c"] <- mat[, 3]
  data[, "names"] <- data$LAST.NAME
  data[, "index"] <- mat[, 4]
  
  for (i in 1:dim(X)[1]) {
    cat(i," ", aff[i], "; " , sep = "")
  }
  
  return(list(affilliations = aff, count = n.aff, data = data))
}

data <- read.csv("Book1.csv", na.strings = c("", NA))
result <- AutoAff(data, "AFFILIATION.1", "AFFILIATION.2", "AFFILIATION.3", "LAST.NAME")
data <- result$data

# for (i in 1:dim(data)[1]) {
  # cat(i," ", result$affilliations[i], "; " , sep = "")
# }

aff.style <- function(first, last, degree, index) {
  first <- as.character(first)
  last <- as.character(last)
  degree <- as.character(degree)
  index <- as.character(index)
  for (i in 1:length(first)) {
    cat(first[i], " ", last[i], ", ", degree[i], index[i], ";", sep = "" )
  }
}
aff.style(first = data$FIRST.NAME,last = data$LAST.NAME, degree = data$DEGREES, index = data$index)
```

`r data$names[1]`^`r which(result$affilliations == data$a[1])`,`r which(result$affilliations == data$b[1])`,`r which(result$affilliations == data$c[1])`^,
`r data$names[2]`^`r which(result$affilliations == data$a[2])`,`r which(result$affilliations == data$b[2])`,`r which(result$affilliations == data$c[2])`^,
`r data$names[3]`^`r which(result$affilliations == data$a[3])`,`r which(result$affilliations == data$b[3])`,`r which(result$affilliations == data$c[3])`^,
`r data$names[4]`^`r which(result$affilliations == data$a[4])`,`r which(result$affilliations == data$b[4])`,`r which(result$affilliations == data$c[4])`^,
`r data$names[5]`^`r which(result$affilliations == data$a[5])`,`r which(result$affilliations == data$b[5])`,`r which(result$affilliations == data$c[5])`^,
`r data$names[6]`^`r which(result$affilliations == data$a[6])`,`r which(result$affilliations == data$b[6])`,`r which(result$affilliations == data$c[6])`^,
`r data$names[7]`^`r which(result$affilliations == data$a[7])`,`r which(result$affilliations == data$b[7])`,`r which(result$affilliations == data$c[7])`^,
`r data$names[8]`^`r which(result$affilliations == data$a[8])`,`r which(result$affilliations == data$b[8])`,`r which(result$affilliations == data$c[8])`^,
`r data$names[9]`^`r which(result$affilliations == data$a[9])`,`r which(result$affilliations == data$b[9])`,`r which(result$affilliations == data$c[9])`^,
`r data$names[10]`^`r which(result$affilliations == data$a[10])`,`r which(result$affilliations == data$b[10])`,`r which(result$affilliations == data$c[10])`^,
`r data$names[11]`^`r which(result$affilliations == data$a[11])`,`r which(result$affilliations == data$b[11])`,`r which(result$affilliations == data$c[11])`^,
`r data$names[12]`^`r which(result$affilliations == data$a[12])`,`r which(result$affilliations == data$b[12])`,`r which(result$affilliations == data$c[12])`^,
`r data$names[13]`^`r which(result$affilliations == data$a[13])`,`r which(result$affilliations == data$b[13])`,`r which(result$affilliations == data$c[13])`^,
`r data$names[14]`^`r which(result$affilliations == data$a[14])`,`r which(result$affilliations == data$b[14])`,`r which(result$affilliations == data$c[14])`^,
`r data$names[15]`^`r which(result$affilliations == data$a[15])`,`r which(result$affilliations == data$b[15])`,`r which(result$affilliations == data$c[15])`^,
`r data$names[16]`^`r which(result$affilliations == data$a[16])`,`r which(result$affilliations == data$b[16])`,`r which(result$affilliations == data$c[16])`^,
`r data$names[17]`^`r which(result$affilliations == data$a[17])`,`r which(result$affilliations == data$b[17])`,`r which(result$affilliations == data$c[17])`^,
`r data$names[18]`^`r which(result$affilliations == data$a[18])`,`r which(result$affilliations == data$b[18])`,`r which(result$affilliations == data$c[18])`^,
`r data$names[19]`^`r which(result$affilliations == data$a[19])`,`r which(result$affilliations == data$b[19])`,`r which(result$affilliations == data$c[19])`^,
`r data$names[20]`^`r which(result$affilliations == data$a[20])`,`r which(result$affilliations == data$b[20])`,`r which(result$affilliations == data$c[20])`^,
`r data$names[21]`^`r which(result$affilliations == data$a[21])`,`r which(result$affilliations == data$b[21])`,`r which(result$affilliations == data$c[21])`^,
`r data$names[22]`^`r which(result$affilliations == data$a[22])`,`r which(result$affilliations == data$b[22])`,`r which(result$affilliations == data$c[22])`^,
`r data$names[23]`^`r which(result$affilliations == data$a[23])`,`r which(result$affilliations == data$b[23])`,`r which(result$affilliations == data$c[23])`^,
`r data$names[24]`^`r which(result$affilliations == data$a[24])`,`r which(result$affilliations == data$b[24])`,`r which(result$affilliations == data$c[24])`^,
`r data$names[25]`^`r which(result$affilliations == data$a[25])`,`r which(result$affilliations == data$b[25])`,`r which(result$affilliations == data$c[25])`^,
`r data$names[26]`^`r which(result$affilliations == data$a[26])`,`r which(result$affilliations == data$b[26])`,`r which(result$affilliations == data$c[26])`^,
`r data$names[27]`^`r which(result$affilliations == data$a[27])`,`r which(result$affilliations == data$b[27])`,`r which(result$affilliations == data$c[27])`^,
`r data$names[28]`^`r which(result$affilliations == data$a[28])`,`r which(result$affilliations == data$b[28])`,`r which(result$affilliations == data$c[28])`^,
`r data$names[29]`^`r which(result$affilliations == data$a[29])`,`r which(result$affilliations == data$b[29])`,`r which(result$affilliations == data$c[29])`^,
`r data$names[30]`^`r which(result$affilliations == data$a[30])`,`r which(result$affilliations == data$b[30])`,`r which(result$affilliations == data$c[30])`^,
`r data$names[31]`^`r which(result$affilliations == data$a[31])`,`r which(result$affilliations == data$b[31])`,`r which(result$affilliations == data$c[31])`^,
`r data$names[32]`^`r which(result$affilliations == data$a[32])`,`r which(result$affilliations == data$b[32])`,`r which(result$affilliations == data$c[32])`^,
`r data$names[33]`^`r which(result$affilliations == data$a[33])`,`r which(result$affilliations == data$b[33])`,`r which(result$affilliations == data$c[33])`^,
`r data$names[34]`^`r which(result$affilliations == data$a[34])`,`r which(result$affilliations == data$b[34])`,`r which(result$affilliations == data$c[34])`^,
`r data$names[35]`^`r which(result$affilliations == data$a[35])`,`r which(result$affilliations == data$b[35])`,`r which(result$affilliations == data$c[35])`^,
`r data$names[36]`^`r which(result$affilliations == data$a[36])`,`r which(result$affilliations == data$b[36])`,`r which(result$affilliations == data$c[36])`^,
`r data$names[37]`^`r which(result$affilliations == data$a[37])`,`r which(result$affilliations == data$b[37])`,`r which(result$affilliations == data$c[37])`^,
`r data$names[38]`^`r which(result$affilliations == data$a[38])`,`r which(result$affilliations == data$b[38])`,`r which(result$affilliations == data$c[38])`^,
`r data$names[39]`^`r which(result$affilliations == data$a[39])`,`r which(result$affilliations == data$b[39])`,`r which(result$affilliations == data$c[39])`^,
`r data$names[40]`^`r which(result$affilliations == data$a[40])`,`r which(result$affilliations == data$b[40])`,`r which(result$affilliations == data$c[40])`^,
`r data$names[41]`^`r which(result$affilliations == data$a[41])`,`r which(result$affilliations == data$b[41])`,`r which(result$affilliations == data$c[41])`^,
`r data$names[42]`^`r which(result$affilliations == data$a[42])`,`r which(result$affilliations == data$b[42])`,`r which(result$affilliations == data$c[42])`^,
`r data$names[43]`^`r which(result$affilliations == data$a[43])`,`r which(result$affilliations == data$b[43])`,`r which(result$affilliations == data$c[43])`^,
`r data$names[44]`^`r which(result$affilliations == data$a[44])`,`r which(result$affilliations == data$b[44])`,`r which(result$affilliations == data$c[44])`^,
`r data$names[45]`^`r which(result$affilliations == data$a[45])`,`r which(result$affilliations == data$b[45])`,`r which(result$affilliations == data$c[45])`^,
`r data$names[46]`^`r which(result$affilliations == data$a[46])`,`r which(result$affilliations == data$b[46])`,`r which(result$affilliations == data$c[46])`^,
`r data$names[47]`^`r which(result$affilliations == data$a[47])`,`r which(result$affilliations == data$b[47])`,`r which(result$affilliations == data$c[47])`^,
`r data$names[48]`^`r which(result$affilliations == data$a[48])`,`r which(result$affilliations == data$b[48])`,`r which(result$affilliations == data$c[48])`^,
`r data$names[49]`^`r which(result$affilliations == data$a[49])`,`r which(result$affilliations == data$b[49])`,`r which(result$affilliations == data$c[49])`^,
`r data$names[50]`^`r which(result$affilliations == data$a[50])`,`r which(result$affilliations == data$b[50])`,`r which(result$affilliations == data$c[50])`^,
`r data$names[51]`^`r which(result$affilliations == data$a[51])`,`r which(result$affilliations == data$b[51])`,`r which(result$affilliations == data$c[51])`^,
`r data$names[52]`^`r which(result$affilliations == data$a[52])`,`r which(result$affilliations == data$b[52])`,`r which(result$affilliations == data$c[52])`^,
`r data$names[53]`^`r which(result$affilliations == data$a[53])`,`r which(result$affilliations == data$b[53])`,`r which(result$affilliations == data$c[53])`^,
`r data$names[54]`^`r which(result$affilliations == data$a[54])`,`r which(result$affilliations == data$b[54])`,`r which(result$affilliations == data$c[54])`^,
`r data$names[55]`^`r which(result$affilliations == data$a[55])`,`r which(result$affilliations == data$b[55])`,`r which(result$affilliations == data$c[55])`^,
`r data$names[56]`^`r which(result$affilliations == data$a[56])`,`r which(result$affilliations == data$b[56])`,`r which(result$affilliations == data$c[56])`^,
`r data$names[57]`^`r which(result$affilliations == data$a[57])`,`r which(result$affilliations == data$b[57])`,`r which(result$affilliations == data$c[57])`^,
`r data$names[58]`^`r which(result$affilliations == data$a[58])`,`r which(result$affilliations == data$b[58])`,`r which(result$affilliations == data$c[58])`^,
`r data$names[59]`^`r which(result$affilliations == data$a[59])`,`r which(result$affilliations == data$b[59])`,`r which(result$affilliations == data$c[59])`^,
`r data$names[60]`^`r which(result$affilliations == data$a[60])`,`r which(result$affilliations == data$b[60])`,`r which(result$affilliations == data$c[60])`^,
`r data$names[61]`^`r which(result$affilliations == data$a[61])`,`r which(result$affilliations == data$b[61])`,`r which(result$affilliations == data$c[61])`^,
`r data$names[62]`^`r which(result$affilliations == data$a[62])`,`r which(result$affilliations == data$b[62])`,`r which(result$affilliations == data$c[62])`^,
`r data$names[63]`^`r which(result$affilliations == data$a[63])`,`r which(result$affilliations == data$b[63])`,`r which(result$affilliations == data$c[63])`^,
`r data$names[64]`^`r which(result$affilliations == data$a[64])`,`r which(result$affilliations == data$b[64])`,`r which(result$affilliations == data$c[64])`^,
`r data$names[65]`^`r which(result$affilliations == data$a[65])`,`r which(result$affilliations == data$b[65])`,`r which(result$affilliations == data$c[65])`^,
`r data$names[66]`^`r which(result$affilliations == data$a[66])`,`r which(result$affilliations == data$b[66])`,`r which(result$affilliations == data$c[66])`^,
`r data$names[67]`^`r which(result$affilliations == data$a[67])`,`r which(result$affilliations == data$b[67])`,`r which(result$affilliations == data$c[67])`^,
`r data$names[68]`^`r which(result$affilliations == data$a[68])`,`r which(result$affilliations == data$b[68])`,`r which(result$affilliations == data$c[68])`^,
`r data$names[69]`^`r which(result$affilliations == data$a[69])`,`r which(result$affilliations == data$b[69])`,`r which(result$affilliations == data$c[69])`^,
`r data$names[70]`^`r which(result$affilliations == data$a[70])`,`r which(result$affilliations == data$b[70])`,`r which(result$affilliations == data$c[70])`^,
`r data$names[71]`^`r which(result$affilliations == data$a[71])`,`r which(result$affilliations == data$b[71])`,`r which(result$affilliations == data$c[72])`^,
`r data$names[72]`^`r which(result$affilliations == data$a[72])`,`r which(result$affilliations == data$b[72])`,`r which(result$affilliations == data$c[72])`^,
`r data$names[73]`^`r which(result$affilliations == data$a[73])`,`r which(result$affilliations == data$b[73])`,`r which(result$affilliations == data$c[73])`^,
`r data$names[74]`^`r which(result$affilliations == data$a[74])`,`r which(result$affilliations == data$b[74])`,`r which(result$affilliations == data$c[74])`^,
`r data$names[75]`^`r which(result$affilliations == data$a[75])`,`r which(result$affilliations == data$b[75])`,`r which(result$affilliations == data$c[75])`^,
`r data$names[76]`^`r which(result$affilliations == data$a[76])`,`r which(result$affilliations == data$b[76])`,`r which(result$affilliations == data$c[76])`^,
`r data$names[77]`^`r which(result$affilliations == data$a[77])`,`r which(result$affilliations == data$b[77])`,`r which(result$affilliations == data$c[77])`^,
`r data$names[78]`^`r which(result$affilliations == data$a[78])`,`r which(result$affilliations == data$b[78])`,`r which(result$affilliations == data$c[78])`^,
`r data$names[79]`^`r which(result$affilliations == data$a[79])`,`r which(result$affilliations == data$b[79])`,`r which(result$affilliations == data$c[79])`^,
`r data$names[80]`^`r which(result$affilliations == data$a[80])`,`r which(result$affilliations == data$b[80])`,`r which(result$affilliations == data$c[80])`^,
`r data$names[81]`^`r which(result$affilliations == data$a[81])`,`r which(result$affilliations == data$b[81])`,`r which(result$affilliations == data$c[81])`^,
`r data$names[82]`^`r which(result$affilliations == data$a[82])`,`r which(result$affilliations == data$b[82])`,`r which(result$affilliations == data$c[82])`^,
`r data$names[83]`^`r which(result$affilliations == data$a[83])`,`r which(result$affilliations == data$b[83])`,`r which(result$affilliations == data$c[83])`^,
`r data$names[84]`^`r which(result$affilliations == data$a[84])`,`r which(result$affilliations == data$b[84])`,`r which(result$affilliations == data$c[84])`^,
`r data$names[85]`^`r which(result$affilliations == data$a[85])`,`r which(result$affilliations == data$b[85])`,`r which(result$affilliations == data$c[85])`^,
`r data$names[86]`^`r which(result$affilliations == data$a[86])`,`r which(result$affilliations == data$b[86])`,`r which(result$affilliations == data$c[86])`^,
`r data$names[87]`^`r which(result$affilliations == data$a[87])`,`r which(result$affilliations == data$b[87])`,`r which(result$affilliations == data$c[87])`^,
`r data$names[88]`^`r which(result$affilliations == data$a[88])`,`r which(result$affilliations == data$b[88])`,`r which(result$affilliations == data$c[88])`^,
`r data$names[89]`^`r which(result$affilliations == data$a[89])`,`r which(result$affilliations == data$b[89])`,`r which(result$affilliations == data$c[89])`^,
`r data$names[90]`^`r which(result$affilliations == data$a[90])`,`r which(result$affilliations == data$b[90])`,`r which(result$affilliations == data$c[90])`^,
`r data$names[91]`^`r which(result$affilliations == data$a[91])`,`r which(result$affilliations == data$b[91])`,`r which(result$affilliations == data$c[91])`^,
`r data$names[92]`^`r which(result$affilliations == data$a[92])`,`r which(result$affilliations == data$b[92])`,`r which(result$affilliations == data$c[92])`^,
`r data$names[93]`^`r which(result$affilliations == data$a[93])`,`r which(result$affilliations == data$b[93])`,`r which(result$affilliations == data$c[93])`^,
`r data$names[94]`^`r which(result$affilliations == data$a[94])`,`r which(result$affilliations == data$b[94])`,`r which(result$affilliations == data$c[94])`^,
`r data$names[95]`^`r which(result$affilliations == data$a[95])`,`r which(result$affilliations == data$b[95])`,`r which(result$affilliations == data$c[95])`^,
`r data$names[96]`^`r which(result$affilliations == data$a[96])`,`r which(result$affilliations == data$b[96])`,`r which(result$affilliations == data$c[96])`^,
`r data$names[97]`^`r which(result$affilliations == data$a[97])`,`r which(result$affilliations == data$b[97])`,`r which(result$affilliations == data$c[97])`^,
`r data$names[98]`^`r which(result$affilliations == data$a[98])`,`r which(result$affilliations == data$b[98])`,`r which(result$affilliations == data$c[98])`^,
`r data$names[99]`^`r which(result$affilliations == data$a[99])`,`r which(result$affilliations == data$b[99])`,`r which(result$affilliations == data$c[99])`^,
`r data$names[100]`^`r which(result$affilliations == data$a[100])`,`r which(result$affilliations == data$b[100])`,`r which(result$affilliations == data$c[100])`^,
`r data$names[101]`^`r which(result$affilliations == data$a[101])`,`r which(result$affilliations == data$b[101])`,`r which(result$affilliations == data$c[101])`^,
`r data$names[102]`^`r which(result$affilliations == data$a[102])`,`r which(result$affilliations == data$b[102])`,`r which(result$affilliations == data$c[102])`^,
`r data$names[103]`^`r which(result$affilliations == data$a[103])`,`r which(result$affilliations == data$b[103])`,`r which(result$affilliations == data$c[103])`^,
`r data$names[104]`^`r which(result$affilliations == data$a[104])`,`r which(result$affilliations == data$b[104])`,`r which(result$affilliations == data$c[104])`^,
`r data$names[105]`^`r which(result$affilliations == data$a[105])`,`r which(result$affilliations == data$b[105])`,`r which(result$affilliations == data$c[105])`^,
`r data$names[106]`^`r which(result$affilliations == data$a[106])`,`r which(result$affilliations == data$b[106])`,`r which(result$affilliations == data$c[106])`^,
`r data$names[107]`^`r which(result$affilliations == data$a[107])`,`r which(result$affilliations == data$b[107])`,`r which(result$affilliations == data$c[107])`^,
`r data$names[108]`^`r which(result$affilliations == data$a[108])`,`r which(result$affilliations == data$b[108])`,`r which(result$affilliations == data$c[108])`^,
`r data$names[109]`^`r which(result$affilliations == data$a[109])`,`r which(result$affilliations == data$b[109])`,`r which(result$affilliations == data$c[109])`^,
`r data$names[110]`^`r which(result$affilliations == data$a[110])`,`r which(result$affilliations == data$b[110])`,`r which(result$affilliations == data$c[110])`^,
`r data$names[111]`^`r which(result$affilliations == data$a[111])`,`r which(result$affilliations == data$b[111])`,`r which(result$affilliations == data$c[111])`^,
`r data$names[112]`^`r which(result$affilliations == data$a[112])`,`r which(result$affilliations == data$b[112])`,`r which(result$affilliations == data$c[112])`^,
`r data$names[113]`^`r which(result$affilliations == data$a[113])`,`r which(result$affilliations == data$b[113])`,`r which(result$affilliations == data$c[113])`^,
`r data$names[114]`^`r which(result$affilliations == data$a[114])`,`r which(result$affilliations == data$b[114])`,`r which(result$affilliations == data$c[114])`^,
`r data$names[115]`^`r which(result$affilliations == data$a[115])`,`r which(result$affilliations == data$b[115])`,`r which(result$affilliations == data$c[115])`^,
`r data$names[116]`^`r which(result$affilliations == data$a[116])`,`r which(result$affilliations == data$b[116])`,`r which(result$affilliations == data$c[116])`^,
`r data$names[117]`^`r which(result$affilliations == data$a[117])`,`r which(result$affilliations == data$b[117])`,`r which(result$affilliations == data$c[117])`^,
`r data$names[118]`^`r which(result$affilliations == data$a[118])`,`r which(result$affilliations == data$b[118])`,`r which(result$affilliations == data$c[118])`^,
`r data$names[119]`^`r which(result$affilliations == data$a[119])`,`r which(result$affilliations == data$b[119])`,`r which(result$affilliations == data$c[119])`^,
`r data$names[120]`^`r which(result$affilliations == data$a[120])`,`r which(result$affilliations == data$b[120])`,`r which(result$affilliations == data$c[120])`^,
`r data$names[121]`^`r which(result$affilliations == data$a[121])`,`r which(result$affilliations == data$b[121])`,`r which(result$affilliations == data$c[121])`^,
`r data$names[122]`^`r which(result$affilliations == data$a[122])`,`r which(result$affilliations == data$b[122])`,`r which(result$affilliations == data$c[122])`^,
`r data$names[123]`^`r which(result$affilliations == data$a[123])`,`r which(result$affilliations == data$b[123])`,`r which(result$affilliations == data$c[123])`^,
`r data$names[124]`^`r which(result$affilliations == data$a[124])`,`r which(result$affilliations == data$b[124])`,`r which(result$affilliations == data$c[124])`^,
`r data$names[125]`^`r which(result$affilliations == data$a[125])`,`r which(result$affilliations == data$b[125])`,`r which(result$affilliations == data$c[125])`^,
`r data$names[126]`^`r which(result$affilliations == data$a[126])`,`r which(result$affilliations == data$b[126])`,`r which(result$affilliations == data$c[126])`^,
`r data$names[127]`^`r which(result$affilliations == data$a[127])`,`r which(result$affilliations == data$b[127])`,`r which(result$affilliations == data$c[127])`^,
`r data$names[128]`^`r which(result$affilliations == data$a[128])`,`r which(result$affilliations == data$b[128])`,`r which(result$affilliations == data$c[128])`^,
`r data$names[129]`^`r which(result$affilliations == data$a[129])`,`r which(result$affilliations == data$b[129])`,`r which(result$affilliations == data$c[129])`^.
